### ISSUE TITLE
Failed to use offical model from tensorflow

### ISSUE THREAD

**Issue by pardont** [h-maac/Xamarin.Android.TensorFlow.Lite#1]
Hi , h-maac,  I tested your sample, it works.  but when I  load model downloaded from tensorflow offical site,  and try to recognize Image, exception throwed:
Java.Lang.IllegalArgumentException: 'Cannot convert between a TensorFlowLite tensor with type UINT8 and a Java object of type [[[F (which is compatible with the TensorFlowLite type FLOAT32).'
![image](https://user-images.githubusercontent.com/2252587/74819130-e1d0fd80-533a-11ea-8e2a-14eb5c38cb9c.png)

The Model:

[mobilenet_v1_1.0_224_quant_and_labels.zip](https://github.com/h-maac/Xamarin.Android.TensorFlow.Lite/files/4224098/mobilenet_v1_1.0_224_quant_and_labels.zip)

**Comment by sebastiankny** [comment]
I would also like to run the project, but seems i get this exception: Java.Lang.NullPointerException
  Message=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

at line 222 of TFLiteObjectDetectionAPIModel.cs : tfLite.RunForMultipleInputsOutputs(inputArray, outputMap);

![image](https://user-images.githubusercontent.com/50146346/74917687-de08ae00-5402-11ea-8bcd-269485829efd.png)

**Comment by pardont** [comment]
@sebastiankny The code has a bug,  TFLiteObjectDetectionAPIModel.CreateJagged(int lay1, int lay2, int lay3) always return null. please change the return as below.

> 
       private static float[][][] CreateJagged(int lay1, int lay2, int lay3)
        {
            var arr = new float[lay1][][];

            for (int i = 0; i < lay1; i++)
            {
                arr[i] = CreateJagged(lay2, lay3);
            }

            //please changed this line
            //return null;
            return arr;
        }

**Comment by sebastiankny** [comment]
> Hi , h-maac, I tested your sample, it works. but when I load model downloaded from tensorflow offical site, and try to recognize Image, exception throwed:
> Java.Lang.IllegalArgumentException: 'Cannot convert between a TensorFlowLite tensor with type UINT8 and a Java object of type [[[F (which is compatible with the TensorFlowLite type FLOAT32).'
> ![image](https://user-images.githubusercontent.com/2252587/74819130-e1d0fd80-533a-11ea-8e2a-14eb5c38cb9c.png)
> 
> The Model:
> 
> [mobilenet_v1_1.0_224_quant_and_labels.zip](https://github.com/h-maac/Xamarin.Android.TensorFlow.Lite/files/4224098/mobilenet_v1_1.0_224_quant_and_labels.zip)

Take a look at https://github.com/tensorflow/tensorflow/issues/20920
Seems like (i copy one of the comments)
TFLiteObjectDetectionAPIModel was recently modified to use a different model, which as additional outputs (see this commit). If you want to continue using mobilenet_v1, pattern your code after the code before that commit. In particular, mobilenet_v1 only has outputLocations and outputClass. It does not have outputScores or numDetections.

Does this describe your issue?

**Comment by h-maac** [comment]
Hey guys!
Unfortunately I am not managing this repo, I have put this here since it was quite problematic to setup and wanted to save fellow people like you from some headache. 

Please feel free to submit a pull request if a breaking change has occurred or wish to help more people by improving it.
